backend:
  name: git-gateway
  branch: main
media_folder: 'src/data/uploads'

collections:
  - name: 'project'
    label: 'Project'
    folder: 'projects'
    create: true
    slug: '{{slug}}'
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
      - label: 'Featured Image'
        name: 'thumbnail'
        widget: 'image'
      - label: 'Rating (scale of 1-5)'
        name: 'rating'
        widget: 'number'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
